/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"
#include "snake.h"
#include <systick.h>
#include <stdlib.h>


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	SystemInit();
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
	RCC->APB1ENR |= RCC_APB1ENR_SPI2EN;



	GPIOC->MODER &= ~(GPIO_MODER_MODER6 | GPIO_MODER_MODER8);//for reset - pc8 and ao- pc6 plain output
	GPIOC->MODER |= (GPIO_MODER_MODER6_0 | GPIO_MODER_MODER8_0);

	//for buttons
	GPIOC->MODER &= ~(GPIO_MODER_MODER1);//Right
	GPIOA->MODER &= ~(GPIO_MODER_MODER1 | GPIO_MODER_MODER4);//Up and down respectively
	GPIOB->MODER &= ~(GPIO_MODER_MODER0);//Left


	//for pb12- cs plain output
	GPIOB->MODER &= ~(GPIO_MODER_MODER12);
	GPIOB->MODER |= (GPIO_MODER_MODER12_0);

	//for pb13-sck and pb15-mosi spi alternate function
	GPIOB->MODER &= ~(GPIO_MODER_MODER13 | GPIO_MODER_MODER15);
	GPIOB->MODER |= (GPIO_MODER_MODER13_1 | GPIO_MODER_MODER15_1);
	GPIOB->AFR[1] &= ~(GPIO_AFRH_AFRH5);
	GPIOB->AFR[1] |= (GPIO_AFRH_AFRH5_0 | GPIO_AFRH_AFRH5_2);
	GPIOB->AFR[1] &= ~(GPIO_AFRH_AFRH7);
	GPIOB->AFR[1] |= (GPIO_AFRH_AFRH7_0 |GPIO_AFRH_AFRH7_2);

	SPI2->CR1 = 0; // reset
	SPI2->CR1 |= SPI_CR1_MSTR;            // master mode
	SPI2->CR1 |= SPI_CR1_BR_2;            // slower baud rate (divide by 32 or so) for first test
	SPI2->CR1 |= SPI_CR1_SSM | SPI_CR1_SSI; // software slave management
	SPI2->CR1 |= SPI_CR1_SPE;             // enable SPI


	GPIOC->BSRR = (1<<8);       // RESET high
	for(volatile int i=0;i<10000;i++);
	GPIOC->BSRR = (1<<(8+16));  // RESET low
	for(volatile int i=0;i<10000;i++);
	GPIOC->BSRR = (1<<8);       // RESET high
	for(volatile int i=0;i<100000;i++); // wait after reset

	lcd_cmd(0x01); // Software reset
	systick_delay(120);
	lcd_cmd(0x11); // Sleep out
	systick_delay(120);
	lcd_cmd(0x3A); lcd_data(0x05); // 16-bit color mode
	lcd_cmd(0x29); // Display ON

	lcd_cmd(0x2A); lcd_data(0); lcd_data(0); lcd_data(0); lcd_data(127); // column addr 0-127
	lcd_cmd(0x2B); lcd_data(0); lcd_data(0); lcd_data(0); lcd_data(159); // row addr 0-159
	lcd_cmd(0x2C); // memory write
	for(uint32_t i=0; i<128*160; i++) {
	    lcd_data(0xDB);
	    lcd_data(0x00);
	}
	while(1)
	{
		Snake snake;
		Food food;
		set_snake(&snake);
		srand(SysTick->VAL);
		spawn_food(&snake,&food);
		while(snake.current_state!=GAME_OVER&&snake.current_state!=WIN)
		  {
		      game_input(&snake);
		      game_tick(&snake,&food);
		      game_render(&snake,&food);
		      systick_delay(200);
		  }
		  if(snake.current_state==GAME_OVER) lcd_cmd(0x28);
	}
}
